# Config file for tree building pipeline
# Genes to build trees from
GENES: ["tRNA-Lys", "tRNA-Ser", "tRNA-Thr", "alaS", "era", "lepA", "nusA", "secG", "secY", "tRNA-Asp", "frr", "ftsY", "infB", "nusG", "pheS", "prfA", "recA", "rplB", "rplC", "rpmA", "rpmI", "rpsC", "rpsD", "ruvB", "smpB", "tRNA-Glu", "ffh", "infC", "rsmH", "secE", "serS", "tsaE", "rpmC", "ruvX", "rpsB", "yajC", "rplA", "rsfS", "hisS", "rpoB", "fmt", "dnaG", "ileS", "leuS", "pheT", "dnaX", "rpoA", "cgtA", ]
