name: shotguntree_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::openjdk=10.0.2
  - conda-forge::python=3.8.3
  - bioconda::iqtree=2.2.0_beta
  - bioconda::muscle=3.8.1551
  - bioconda::raxml=8.2.12
