name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ctbushman/shotguntree:latest

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3.17.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_SNAKEMAKE_SNAKEFMT: true
  
  test-all:
    name: Test CorGE & Tree Building
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: setup-conda
        # You may pin to the exact commit or the version.
        # uses: s-weigand/setup-conda@945fd9e7c92f1efb12634ba552ee0b2ec140a5fd
        uses: s-weigand/setup-conda@v1.1.0
        with:
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: 'bioconda' # optional, default is 
      
      - name: Install Dependencies
        run: |
          python -m pip install -U pytest
          python -m pip install -U pytest-cov
          conda install snakemake
          conda install -c conda-forge mamba

      - name: Run Tests
        run: |
          cd CorGE
          pip install -e .
          pytest --cov .
          cp .coverage ../
          cd ..
          conda list
          pytest .tests/ # Test snakemake pipeline
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      
          
          


