name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format:
    name: Snakefmt Snakefile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install Dependencies
        run: |
          python -m pip install snakefmt

      - name: Run Snakefmt
        run: |
          snakefmt workflow/Snakefile

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3.17.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_SNAKEMAKE_SNAKEFMT: true
  test:
    name: Test Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: setup-conda
        # You may pin to the exact commit or the version.
        # uses: s-weigand/setup-conda@945fd9e7c92f1efb12634ba552ee0b2ec140a5fd
        uses: s-weigand/setup-conda@v1.1.0
        with:
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: 'bioconda' # optional, default is 
      
      - name: Install Dependencies
        run: |
          python -m pip install -U pytest
          python -m pip install snakemake
          conda install -c conda-forge mamba

      - name: Run Tests
        run: |
          pytest .tests/
          
          
          


