name: CI
on: push

jobs:
  format:
    name: Snakefmt Snakefile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install Dependencies
        run: |
          python -m pip install snakefmt

      - name: Run Snakefmt
        run: |
          snakefmt workflow/Snakefile

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3.17.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_SNAKEMAKE_SNAKEFMT: true
  test:
    name: Test Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install Dependencies
        run: |
          python -m pip install -U pytest
          python -m pip install snakemake

      - name: Run Tests
        run: |
          pytest .tests/
      
      - name: Testing
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
          stagein: '' # additional preliminary commands to run (can be multiline)



